[package]
name = "alfatch_vmc"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
byteorder = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
tempfile = "3.21.0"
